### ISSUE TITLE
Ops automator failure notification

### ISSUE THREAD

**Issue by ashwin-ke** [awslabs/aws-ops-automator#11]
Hi ,
I have setup opsautomator in our aws eu-west-1 accounts. It has been working fine for us. I have subscribed to notification in case of failures in opsautomator. But few days back i got a lot of alerts of some failures. This json text and the subsequent python stack trace is not decipherable to me to know what happened. I reached out to aws premium support and they said they don't support code issues and pointed me to here. Can you please help me decipher if there is a problem with opsautomator and what action can i take to mitigate this ?
[opsauto-error-sns-githubpost-04082018-2100ist.txt](https://github.com/awslabs/aws-ops-automator/files/2259612/opsauto-error-sns-githubpost-04082018-2100ist.txt)
The attached text file has the complete error details as i received.

Thank you,

with regards,
ashwin

**Comment by arieleeuw** [comment]
Ashwin,

Looking into this one. This situation can happen in eventually consistent situations and should not affect the working of Ops Automator. But as it can cause confusion I will update the code in our next release to and handle this better. Thanks, for your detailed info that helped me to track this one

Arie

**Comment by AndrewCi** [comment]
Has there been any progress on this? I've been receiving this error a lot recently.

**Comment by maykays** [comment]
Will not fix. We're shifting our development priority to [Operations Conductor](https://github.com/awslabs/operations-conductor). You are welcome to fork the solution to make updates.
