### ISSUE TITLE
RDS Snapshot Capability / V2 Release Dates?

### ISSUE THREAD

**Issue by AndrewCi** [awslabs/aws-ops-automator#12]
Hi -

I am looking into developing a custom action built on top of the AWS Ops Automator framework for scheduling RDS snapshots.

Is this planned to be included in V2 and is there a set date for when V2 will be released? Don't want to go through the development effort if this is planned in the next version.

Best,
Andrew

**Comment by arieleeuw** [comment]
Hi Andrew,

In V2 we will a large set of new actions. These will include a set of actions to create/copy and delete RDS snapshots.
We're in the finishing and testing phase of V2 and we have not set a public release day yet.

regards,
Arie

**Comment by AndrewCi** [comment]
Thank you for getting back to me. I do have one followup - I'm building a notification processor to handle the error messages sent to SNS to better filter errors to stakeholders. For example, notifying the owner of a resource if their specific EBS volume snapshot failed based on EBS volume tag or notifying an account owner if an error occurred in a specific account. 

Is there any documentation on what the SNS error messages look like and what information they supply? Was having trouble backing it out from the source code. Or would you reccomendation a different path (such as pulling from Cloud Watch log group directly or one of the Dynamodb tables)? 

Thank you in advance.
