### ISSUE TITLE
Tag Filtering Clarification - (1) Multiple Values for Same Key (2) And/Or

### ISSUE THREAD

**Issue by AndrewCi** [awslabs/aws-ops-automator#13]
Hi AWS Labs Team -

I had two quick tag filtering clarifications. See below:

(1) How do I specify multiple value filters for the same key filter? Is <namefilter>=<valuefilter1>,<valuefilter2> valid? Or do I need to separate out <namefilter>=<valuefilter1> and <namefilter>=<valuefilter2>?

(2) Is it possible to create an "AND" relationship instead of an "OR" relationship between filters. For example, I want to filter resources that have both <namefilter1>=<valuefilter1> AND <namefilter2>=<valuefilter2>? It is my current understanding <namefilter1>=<valuefilter1>, <namefilter2>=<valuefilter2> produces an "OR" relationship. 

Thank you in advance for the clarification.

Best,
Andrew

**Comment by arieleeuw** [comment]
(1) a=b,a=c will return true if the tag a has a value a or c, as you mentioned the "," acts as an OR operator

you can also consider to use a regex for the value by using a "\" prefix for the value; "key=\a|b"

(2)
In Ops Automator V2 we have full boolean logic, including; AND, OR and ! (not)

We have extended the syntax so this allows you to have expressions like this:

((A=*&B=*)|C=*)      Tag A and B or Tag C
(!A=*)&(C=!D)          No Tag A and Tag C with value != D

regards,
Arie

**Comment by maykays** [comment]
Closing this ticket as it appears the question has been answered.
