### ISSUE TITLE
Error writing to logstream

### ISSUE THREAD

**Issue by AndrewCi** [awslabs/aws-ops-automator#16]
I am continually receiving the error "Error writing to logstream OpsAutomatorMain-20181216 (An error occurred (InvalidSequenceTokenException) when calling the PutLogEvents operation: The given sequenceToken is invalid. The next expected sequenceToken is: 49587344250979592942391387075837745078173907632500425906)".

This only started happening since December 15th. I've also looked at the Lambda metrics and there is a spike in invocations and runtime duration. This is not correlated to any significant change in our AWS environment.

Thoughts?

**Comment by AndrewCi** [comment]
It appears this was being caused by the "completion_handler.py" class not functioning properly. It was processing tasks that were marked as "Completed", but not removing these as incomplete. Have you seen this issue before?

**Comment by arieleeuw** [comment]
We have identified this issue. To verify can you please send the part of the log streams that show any errors, if any, related to the issue you describe in the second message. 
The logging issue is addressed in an upcoming maintenance, as well as a major V2 update,  that are currently in test, for which we have in limited preview for non-production environments .

**Comment by AndrewCi** [comment]
![image](https://user-images.githubusercontent.com/10524644/50182346-17b0c700-02dd-11e9-98d1-383d61a3ebbf.png)

You can see the logs above. For whatever reason, it was not closing out tasks marked as "Completed"  and was continually invoking the Lambda and scanning the DynamoDB table for incomplete tasks and setting new completion times. 

This was causing the CompletionRule CloudWatch event to run continuously every 1 minute and was never programmatically disabled. I had to manually clear the DynamoDB table WaitForCompletionTasks DynamoDB table index - it had accrued a large number of completed tasks in this waitforcompletion index.

I have a case with AWS Enterprise support ticket open now if you can access it (Case ID5614735461).

**Comment by maykays** [comment]
Will not fix. We're shifting our development priority to [Operations Conductor](https://github.com/awslabs/operations-conductor). You are welcome to fork the solution to make updates.
