### ISSUE TITLE
Ec2CreateSnapshot.template fails to deploy with default settings

### ISSUE THREAD

**Issue by schottsfired** [awslabs/aws-ops-automator#17]
Hello,
I followed the [instructions](https://docs.aws.amazon.com/solutions/latest/ops-automator/deployment.html) for deploying Ops Automator and the stack deployed successfully. On step 2, I chose `Ec2CreateSnapshot.template` from the `Configuration` S3 bucket. I then created a stack from this template, only filling out required parameters like stack name and crontab. Left everything else as-is.

The wizard throws the following error:
`Parameter 'GlobalSecondaryIndexWrite1' must be a number.`

Tried adding numbers to all fields but no change in behavior.

Appreciate your help in advance.

Thanks,

**Comment by arieleeuw** [comment]
Can you check if you're running the correct action/template as this parameter is for the dynamodb_set_capacity action.

**Comment by schottsfired** [comment]
Hi @arieleeuw - you are right! The error was produced by a different template. No idea how I missed that, and I'm sorry to waste your time. Thanks for the solution!
