### ISSUE TITLE
Issue with delete snapshot template

### ISSUE THREAD

**Issue by karan1507** [awslabs/aws-ops-automator#20]
Hello Team,

I have contacted the AWS Premium support for this issue and they have given me your reference.
I have deployed the Whole OPS Automator while being on a screen sharing session with the AWS Support team but still facing the same issue. Below are the details:

I have deployed the whole Ops Automator.
1) Create Snapshot on an Hourly and daily basis is working fine for me.
2) I want to delete the created snapshots after 35 days. But it is not deleting the snapshot. We need to address this issue because it is incurring a huge cost to us.
3) There are no entries such as Delete Snapshots in the task tracking table of Dynamo DB.

Can you please provide a solution to this.

Attaching the snippets
<img width="344" alt="Capture" src="https://user-images.githubusercontent.com/45931951/56128775-3dee2700-5f9e-11e9-8f06-855d21e3e179.PNG">
<img width="544" alt="Capture1" src="https://user-images.githubusercontent.com/45931951/56128776-3e86bd80-5f9e-11e9-8ba4-d2c8df7abf53.PNG">
<img width="403" alt="Capture3" src="https://user-images.githubusercontent.com/45931951/56128777-3e86bd80-5f9e-11e9-99f1-48230480cafb.PNG">

**Comment by jacobliuat** [comment]
Please try to set up the lambda function timeout from 5 minutes to 15 minutes and monitor if it works.

**Comment by georgebearden** [comment]
Hi @karan1507 - The suggestion by @jacobliuat is what I would recommend at first also. Given the inactivity here I'm going to close this issue but please let me know if you need additional assistance.
