### ISSUE TITLE
Delete snapshot error when there is too much snapshot

### ISSUE THREAD

**Issue by marouenrebani** [awslabs/aws-ops-automator#23]
Hello.

I noticed that when ops automator delete-snapshot task is used on lot of snapshot it does not work (I don't know the threshold).

I got his error in lambda:
`TART RequestId: 2c12a9e2-5dff-4dcc-954a-d5ad44fb6af3 Version: $LATEST
('Error building log subject for action class 
{}
, 
{}
', "<class 'actions.ec2_delete_snapshot_action.Ec2DeleteSnapshotAction'>", KeyError('ActionId'))
{'MessageId': 'ecc03a95-a419-51e2-8add-6cc29b770354', 'ResponseMetadata': {'RequestId': 'c738bd0d-240f-56d3-9d55-eb5a1b619465', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'c738bd0d-240f-56d3-9d55-eb5a1b619465', 'content-type': 'text/xml', 'content-length': '294', 'date': 'Tue, 26 Nov 2019 14:56:46 GMT'}, 'RetryAttempts': 0}}
END RequestId: 2c12a9e2-5dff-4dcc-954a-d5ad44fb6af3
REPORT RequestId: 2c12a9e2-5dff-4dcc-954a-d5ad44fb6af3	Duration: 4316.03 ms	Billed Duration: 4400 ms	Memory Size: 1024 MB	Max Memory Used: 127 MB	`

I tried to run it on a big lambda but it is not a memory issue nor a time out issue.

Thank you.

Marouen

**Comment by dzhu-fasttrack** [comment]
Hello,

We had recently set up the Ops Automator and had run into this similar issue in regards to deleting a lot of snapshots which produced the same error. When we enabled debug we found the following error message under the log group which houses the logs for the automator tasks:

ERROR   : Error execution of execute-action for task OpsAutomator-14Day-Snapshot-Remover
 name 's' is not defined
Traceback (most recent call last):
  File "/var/runtime/bootstrap", line 12, in <module>
    main()
  File "/var/runtime/bootstrap.py", line 361, in main
    event_request.deadline_time_in_ms)
  File "/var/runtime/bootstrap.py", line 131, in handle_event_request
    response = request_handler(event, lambda_context)
  File "/var/task/main.py", line 94, in lambda_handler
    result = handler.handle_request()
  File "/var/task/handlers/execution_handler.py", line 480, in handle_request
    return self._handle_task_execution()
  File "/var/task/handlers/execution_handler.py", line 279, in _handle_task_execution
    action_result = self._action_instance.execute()
  File "/var/task/actions/ec2_delete_snapshot_action.py", line 316, in execute
    for deleted_snapshot in snapshots_to_delete():
  File "/var/task/actions/ec2_delete_snapshot_action.py", line 299, in snapshots_to_delete
    return list(by_retention_days()) if self.retention_days != 0 else list(by_retention_count())
  File "/var/task/actions/ec2_delete_snapshot_action.py", line 267, in by_retention_days
    self._logger_.debug(DEBUG_SN_RETENTION_DAYS_KEEP, sn, s, ["VolumeId"],
NameError: name 's' is not defined

Looking back at the Lambda function action which was used to run this task, ec2_delete_snapshot_action.py, and looking around line 267 as indicated by the traceback we believe the line "self._logger_.debug(DEBUG_SN_RETENTION_DAYS_KEEP, sn, s, ["VolumeId"]," did not seem right. After modifying the line to "self._logger_.debug(DEBUG_SN_RETENTION_DAYS_KEEP, sn["SnapshotId"], get_start_time(sn), sn["VolumeId"], delete_before_dt.isoformat())" similar to the if statement above it we found that the task started working again, although the Log group for lamdba function used still had the error building log subject for action class error.

@marouenrebani 
Not sure if you are still having this issue, but you could see if the above works for you.

If the project owner of Ops Automator could verify if my findings are correct or not that would be good.

Kind regards,
Daniel Zhu

**Comment by maykays** [comment]
Will not fix. We're shifting our development priority to [Operations Conductor](https://github.com/awslabs/operations-conductor). You are welcome to fork the solution to make updates.
