### ISSUE TITLE
Issue with CreateSnapsshot action in OpsAutomator version 1.1.2.34

### ISSUE THREAD

**Issue by razhamma** [awslabs/aws-ops-automator#24]
Description:
--------------
- Currently deployed is Ops Automator version `1.1.2.34`
- Snapshots were being taken as per scheduled and last snapshot was taken on `12th March, 2020`.
- Suddenly, OpsAutomator stopped taking snapshots.

Observations:
---------------
- Checking through CloudTrail logs, last `CreateSnapshot` API call was made on `12th March, 2020`.
- CloudWatch log streams in respective log group for lambda in primary account doesn't show much of info.
- However, Lambda is being invoked as per schedule daily and respective logstream is being created.
- Permissions are fine with the role in secondary account to take snapshot.

Questions:
------------
- OpsAutomator version `1.1.2.34` was python2.7 based but current OpsAutomator version is `2.1.x` and its python3.7 based. As python2.7 has faced its EOL, could it be the affecting reason in this case?
- As Lambda is still being invoked and respective logstream is being created, shouldn't this solution be able to log exact error message in the logstream if its failing for some reason?

**Comment by rakshb** [comment]
Hello @razhamma. We suggest that you update to the latest version on OpsAutomator to stop experiencing this snapshot issue.
Our recommendation is to try to migrate to the solution's successor OpsConductor for best results
https://aws.amazon.com/solutions/implementations/operations-conductor/

**Comment by maykays** [comment]
Closing this issue.  Please re-open if you continue to face this problem after updating to the latest version of the solution.
