### ISSUE TITLE
Ops Automator Action Developers guide

### ISSUE THREAD

**Issue by guessmyname** [awslabs/aws-ops-automator#25]
The documentation [refers ](https://github.com/awslabs/aws-ops-automator/blob/master/README.md#the-ops-automator-framework-handles-the-following-functionality)to Ops Automator Action Developers guide. I can't find this anywhere. Is this available?

**Comment by rakshb** [comment]
Hello @guessmyname The Developers guide is the same as the Implementation Guide which is provided on solution landing page https://docs.aws.amazon.com/solutions/latest/ops-automator/welcome.html

**Comment by guessmyname** [comment]
I am not seeing how to develop Custom Actions in the implementation Guide. Am I missing something or does this mean that the framework is not intended for customization?

**Comment by maykays** [comment]
@guessmyname You can customize the Ops Automator solution. Please refer to the [Implementation Guide](https://docs.aws.amazon.com/solutions/latest/ops-automator/appendix-a.html) and examples included in the appendices.
